# Generated by Django 4.1.7 on 2023-03-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_smartphone_add_date_smartphone_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='memory',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(max_length=10),
        ),
    ]
