# Generated by Django 4.1.7 on 2023-03-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_smartphone_memory_alter_smartphone_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
